"""Story-method emotion-vector derivation (Sofroniew et al. 2026).

Implements the paper's derivation procedure from
``docs/EmotionConcepts.pdf`` as a parallel pipeline to the project's
existing CAA-style derivation in
``src.llm_psych.probes.derive_steering_vector``.

The paper's recipe (per the "Extracting emotion vectors" section):

1. Generate synthetic stories in which characters experience the target
   emotion. Stories are generated by the target model itself.
2. Extract residual-stream activations at each candidate layer, averaging
   across token positions ``>= 50`` within each story.
3. Per emotion, compute the mean activation across that emotion's
   stories.
4. **Cross-emotion centering**: subtract the mean activation taken
   across all emotions (not against a separate neutral set).
5. **Confound removal**: project the resulting vectors orthogonal to
   the top principal components of activations on an emotionally
   neutral transcript set (PCs explaining ``>= var_threshold`` variance,
   typically 0.5).

This module exposes pure-NumPy primitives for steps 3-5. Story
generation and activation extraction (steps 1-2) live in dedicated
scripts under ``scripts/``.

The existing CAA derivation in ``probes.derive_steering_vector`` is
untouched and remains the project's pre-registered H1/H2 path.
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "derive_story_vectors",
    "fit_neutral_pcs",
    "project_out",
    "derive_paper_steering_vectors",
]


def derive_story_vectors(
    per_emotion_acts: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Compute centered emotion vectors via cross-emotion-mean subtraction.

    For each emotion ``e`` with stacked story-level activations
    ``X_e ∈ R^{n_e × d}`` (already pooled to one vector per story):

    .. math::

        v_e = \\text{mean}(X_e) - \\text{mean}_{\\text{all emotions}}(\\text{mean}(X_e))

    The per-emotion mean is computed first; then the grand mean is taken
    over the per-emotion means (each emotion contributes equally,
    independent of how many stories were generated per emotion).

    Parameters
    ----------
    per_emotion_acts
        Mapping ``emotion_name -> activations`` where each value is a
        float array of shape ``(n_stories, hidden_dim)`` for that emotion
        at a single layer. All values must share ``hidden_dim``.

    Returns
    -------
    dict[str, np.ndarray]
        Mapping ``emotion_name -> v_e`` of shape ``(hidden_dim,)`` in
        float32. Same keys as the input.

    Raises
    ------
    ValueError
        If the input dict is empty or hidden dims disagree across
        emotions.
    """
    if not per_emotion_acts:
        raise ValueError("per_emotion_acts must contain at least one emotion.")

    means: dict[str, np.ndarray] = {}
    hidden_dim: int | None = None
    for name, acts in per_emotion_acts.items():
        arr = np.asarray(acts, dtype=np.float64)
        if arr.ndim != 2:
            raise ValueError(
                f"Activations for '{name}' must be 2-D (n_stories, hidden_dim); "
                f"got shape {arr.shape}."
            )
        if hidden_dim is None:
            hidden_dim = arr.shape[1]
        elif arr.shape[1] != hidden_dim:
            raise ValueError(
                f"Hidden-dim mismatch for emotion '{name}': "
                f"expected {hidden_dim}, got {arr.shape[1]}."
            )
        means[name] = arr.mean(axis=0)

    grand_mean = np.mean(np.stack(list(means.values()), axis=0), axis=0)
    return {name: (m - grand_mean).astype(np.float32) for name, m in means.items()}


def fit_neutral_pcs(
    neutral_acts: np.ndarray,
    var_threshold: float = 0.5,
) -> np.ndarray:
    """Compute the top principal components of a neutral activation set.

    PCs are returned as an orthonormal basis spanning the directions
    that explain at least ``var_threshold`` of the total variance.
    Mean-centering is applied prior to SVD.

    Parameters
    ----------
    neutral_acts
        Float array of shape ``(n_samples, hidden_dim)``. Pooled
        story-level activations on emotionally neutral transcripts at
        a single layer.
    var_threshold
        Fraction of variance (in ``(0, 1]``) that the returned basis
        must explain. Default ``0.5`` per the paper.

    Returns
    -------
    np.ndarray
        Array of shape ``(k, hidden_dim)``, float32, where ``k`` is the
        smallest number of PCs whose cumulative explained-variance
        ratio reaches ``var_threshold``. Rows are orthonormal.

    Raises
    ------
    ValueError
        If ``neutral_acts`` is not 2-D, or ``var_threshold`` is outside
        ``(0, 1]``.
    """
    if not 0.0 < var_threshold <= 1.0:
        raise ValueError(
            f"var_threshold must lie in (0, 1]; got {var_threshold!r}."
        )
    X = np.asarray(neutral_acts, dtype=np.float64)
    if X.ndim != 2:
        raise ValueError(
            f"neutral_acts must be 2-D (n_samples, hidden_dim); got shape {X.shape}."
        )

    X_centered = X - X.mean(axis=0, keepdims=True)
    # SVD on the centered data matrix:
    #   X = U S V^T,  with V^T rows = principal axes (eigenvectors of cov).
    # Singular values squared correspond to total variance (up to a 1/(n-1)
    # factor, which cancels in the ratio).
    _, s, vt = np.linalg.svd(X_centered, full_matrices=False)
    explained = (s ** 2) / np.sum(s ** 2)
    cumulative = np.cumsum(explained)
    # Smallest k with cumulative[k-1] >= var_threshold.
    k = int(np.searchsorted(cumulative, var_threshold) + 1)
    k = min(k, vt.shape[0])
    return vt[:k].astype(np.float32)


def project_out(vectors: np.ndarray, basis: np.ndarray) -> np.ndarray:
    """Remove the column-space of ``basis`` from each row of ``vectors``.

    Given an orthonormal basis ``B ∈ R^{k × d}`` (rows orthonormal) and
    vectors ``V ∈ R^{n × d}``:

    .. math::

        V' = V - V B^T B

    For a single vector input of shape ``(d,)`` the result is also 1-D.

    Parameters
    ----------
    vectors
        Float array of shape ``(n, d)`` or ``(d,)``.
    basis
        Float array of shape ``(k, d)`` whose rows are (approximately)
        orthonormal. ``fit_neutral_pcs`` produces such a basis.

    Returns
    -------
    np.ndarray
        Same shape and float32 dtype as ``vectors`` (cast on output).
    """
    V = np.asarray(vectors, dtype=np.float64)
    B = np.asarray(basis, dtype=np.float64)
    if B.ndim != 2:
        raise ValueError(f"basis must be 2-D; got shape {B.shape}.")
    if V.shape[-1] != B.shape[1]:
        raise ValueError(
            f"hidden-dim mismatch: vectors last-axis={V.shape[-1]}, "
            f"basis cols={B.shape[1]}."
        )

    squeeze = V.ndim == 1
    if squeeze:
        V = V[np.newaxis, :]

    # V' = V - (V @ B^T) @ B
    coeffs = V @ B.T  # (n, k)
    V_proj = V - coeffs @ B  # (n, d)
    result = V_proj.astype(np.float32)
    return result[0] if squeeze else result


def derive_paper_steering_vectors(
    per_emotion_acts: dict[str, np.ndarray],
    neutral_acts: np.ndarray,
    *,
    var_threshold: float = 0.5,
) -> dict[str, np.ndarray]:
    """End-to-end paper-style derivation at a single layer.

    Composes :func:`derive_story_vectors` and :func:`project_out` using
    PCs fit by :func:`fit_neutral_pcs` on the neutral activation set.

    Parameters
    ----------
    per_emotion_acts
        Mapping ``emotion_name -> (n_stories, hidden_dim)`` arrays at
        one layer. See :func:`derive_story_vectors`.
    neutral_acts
        ``(n_neutral, hidden_dim)`` array at the same layer.
    var_threshold
        Forwarded to :func:`fit_neutral_pcs`. Default ``0.5``.

    Returns
    -------
    dict[str, np.ndarray]
        Mapping ``emotion_name -> v_e ∈ R^{hidden_dim}`` (float32),
        cross-emotion centered and projected orthogonal to the neutral
        PCs.

    Notes
    -----
    Hidden-dim consistency between ``per_emotion_acts`` and
    ``neutral_acts`` is enforced by :func:`project_out`.
    """
    raw = derive_story_vectors(per_emotion_acts)
    pcs = fit_neutral_pcs(neutral_acts, var_threshold=var_threshold)
    stacked = np.stack(list(raw.values()), axis=0)  # (n_emotions, hidden_dim)
    cleaned = project_out(stacked, pcs)
    return {name: cleaned[i] for i, name in enumerate(raw.keys())}
