#!/usr/bin/env python3
"""Phase-1 readout for J-space decomposition of story-method emotion vectors.

Reads the manifests produced by scripts/decompose_emotion_vectors.py and
prints/plots the key descriptive diagnostics from plans/j-space-decomposition.md:

1. J-space variance fraction at the locked C2 validation layers.
2. Mean J-space fraction across the swept layer grid.
3. Digit-atom capture in admiration's J-space reconstruction.

Outputs are written to results/jspace_phase1_readout/.
"""
from __future__ import annotations

import re
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import yaml

matplotlib.use("Agg")

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "results" / "jspace_phase1_readout"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FOLDERS = {
    "Llama-3.1-8B-Instruct-story": "Llama-3.1-8B-Instruct",
    "Qwen2.5-7B-Instruct-story": "Qwen2.5-7B-Instruct",
    "gemma-2-9b-it-story": "gemma-2-9b-it",
}


def is_digit_token(tok: str) -> bool:
    """Heuristic for a digit token across SentencePiece-style vocabularies."""
    s = tok.replace("Ġ", "").replace("▁", "").strip()
    return bool(re.fullmatch(r"\d+", s))


def load_manifest(folder: str) -> dict:
    path = ROOT / "results" / "workspace_decomposition" / folder / "manifest.yaml"
    return yaml.safe_load(path.read_text())


def build_table(locked: dict) -> pd.DataFrame:
    rows = []
    for folder, model_key in FOLDERS.items():
        manifest = load_manifest(folder)
        model_locked = locked["models"][model_key]
        for emotion, layers in manifest["vectors"].items():
            locked_layer = model_locked["emotions"][emotion].get("layer")
            for lyr_s, info in layers.items():
                lyr = int(lyr_s)
                m = info["metrics_pos"]
                tokens = m["tokens"]
                coefs = m["coefs"]
                digit_mask = [is_digit_token(t) for t in tokens]
                digit_coef_sum = sum(c for c, d in zip(coefs, digit_mask, strict=False) if d)
                total_coef_sum = sum(coefs)
                rows.append(
                    {
                        "model": model_key,
                        "emotion": emotion,
                        "layer": lyr,
                        "locked": lyr == locked_layer,
                        "frac": m["frac_norm_squared"],
                        "digit_count": sum(digit_mask),
                        "digit_coef_frac": (
                            digit_coef_sum / total_coef_sum
                            if total_coef_sum
                            else 0.0
                        ),
                    }
                )
    return pd.DataFrame(rows)


def main() -> None:
    locked = yaml.safe_load(
        (ROOT / "configs" / "vector_validation" / "layers.yaml").read_text()
    )
    df = build_table(locked)

    print("\n=== J-space fraction at locked layers ===")
    print(df[df["locked"]][
        ["model", "emotion", "layer", "frac", "digit_coef_frac"]
    ].to_string(index=False))

    print("\n=== Mean J-space fraction across swept layers ===")
    print(df.groupby(["model", "emotion"])["frac"].mean().unstack().to_string())

    print("\n=== Admiration digit-atom capture (count / 16, coefficient fraction) ===")
    adm = df[df["emotion"] == "admiration"].sort_values(["model", "layer"])
    print(adm[["model", "layer", "digit_count", "digit_coef_frac", "frac"]].to_string(index=False))

    fig, axes = plt.subplots(2, 2, figsize=(12, 10), sharex=True, sharey=True)
    axes = axes.ravel()
    for ax, (model, sub) in zip(axes, df.groupby("model"), strict=False):
        for emotion, sub2 in sub.groupby("emotion"):
            ax.plot(sub2["layer"], sub2["frac"], marker="o", label=emotion)
        ax.set_title(model)
        ax.set_xlabel("layer")
        ax.set_ylabel("J-space fraction (variance)")
        ax.legend()
        ax.set_ylim(0, max(df["frac"].max() * 1.05, 0.05))
    fig.delaxes(axes[3])
    plt.tight_layout()
    plot_path = OUTPUT_DIR / "jspace_fraction_by_layer.png"
    plt.savefig(plot_path, dpi=150)
    print(f"\nSaved plot: {plot_path}")

    def _to_md(frame: pd.DataFrame, *, float_fmt: str = ".4f") -> str:
        return frame.to_string(index=False, float_format=lambda x: f"{x:{float_fmt}}")

    summary_path = OUTPUT_DIR / "phase1_summary.md"
    summary_path.write_text(
        "# J-space phase-1 readout summary\n\n"
        "Generated by `scripts/analyze_jspace_phase1.py`.\n\n"
        "## J-space fraction at locked layers\n\n"
        "```\n"
        + _to_md(df[df["locked"]][["model", "emotion", "layer", "frac"]])
        + "\n```\n\n## Mean J-space fraction across swept layers\n\n"
        "```\n"
        + df.groupby(["model", "emotion"])["frac"].mean().unstack().to_string(
            float_format=lambda x: f"{x:.4f}"
        )
        + "\n```\n\n## Admiration digit-atom capture\n\n"
        "```\n"
        + _to_md(adm[["model", "layer", "digit_count", "digit_coef_frac", "frac"]])
        + "\n```\n"
    )
    print(f"Saved summary: {summary_path}")


if __name__ == "__main__":
    main()
