"""Generate the Sofroniew-paper add-on emotion configs from ``configs/wheel_paper.yaml``.

Writes one Hydra emotion config per enabled paper cell to
``configs/emotion/paper_<name>.yaml``. The ``paper_`` prefix keeps these
out of the ``wheel_*`` glob that ``scripts/run_wheel.sh`` uses, so the
frozen story-wheel32 track cannot pick them up by accident, and off the
bare ``<name>.yaml`` legacy configs (``calm.yaml`` and ``desperate.yaml``
already exist for the CAA/probe track and use the old
``prompt_file``/``label`` schema).

Like ``scripts/build_wheel_configs.py``, ``name`` is the bare cell name
because ``cfg.emotion.name`` is what the pipeline uses for corpus and
activation filenames *and* what goes into the generation prompt; the
track path component keeps the sets apart.

Usage::

    uv run python scripts/build_paper_emotion_configs.py [--check]
    uv run python scripts/build_paper_emotion_configs.py --list-enabled
    uv run python scripts/build_paper_emotion_configs.py --print-track

``--check`` regenerates into memory and exits non-zero if any file on
disk differs, for CI. ``--list-enabled`` prints the enabled config stems
(one per line, e.g. ``paper_calm``) for shell callers; ``--print-track``
prints the track name, so ``scripts/run_paper_emotions.sh`` never has to
parse YAML itself.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SPEC = _REPO_ROOT / "configs" / "wheel_paper.yaml"
_WHEEL_SPEC = _REPO_ROOT / "configs" / "wheel.yaml"
_OUT_DIR = _REPO_ROOT / "configs" / "emotion"
_PREFIX = "paper_"


def load_spec(path: Path = _SPEC) -> dict:
    """Read and validate ``configs/wheel_paper.yaml``."""
    spec = yaml.safe_load(path.read_text())

    for key in ("track", "base_track", "cells"):
        if key not in spec:
            raise ValueError(f"{path.name} is missing required key: {key}")
    if not spec["cells"]:
        raise ValueError(f"{path.name} defines no cells")

    labels = [c["label"] for c in spec["cells"]]
    if len(set(labels)) != len(labels):
        raise ValueError("duplicate labels in wheel_paper.yaml")
    if any(not 200 <= label < 300 for label in labels):
        raise ValueError("paper cell labels must live in the 200-block")

    # Names must not collide with a wheel cell: both sets share one track's
    # corpus/activation namespace, so a duplicate name would silently make
    # one corpus overwrite the other.
    wheel_names = _wheel_cell_names()
    for cell in spec["cells"]:
        if cell["name"] in wheel_names:
            raise ValueError(
                f"paper cell {cell['name']!r} collides with a wheel cell name; "
                "the two sets share the track's corpus namespace"
            )
    return spec


def _wheel_cell_names() -> set[str]:
    """Every cell name in the wheel spec (24 ring + 8 dyad + neutral)."""
    wheel = yaml.safe_load(_WHEEL_SPEC.read_text())
    names = {wheel["neutral"]["name"]}
    for axis in wheel["axes"]:
        names.update(axis["rings"].values())
    names.update(dyad["name"] for dyad in wheel["dyads"])
    return names


def enabled_cells(spec: dict) -> list[dict]:
    """Cells with ``enabled: true``, in spec order."""
    return [c for c in spec["cells"] if c.get("enabled", False)]


def render(cell: dict, spec: dict) -> str:
    """Render one emotion config file."""
    head = (
        "# GENERATED by scripts/build_paper_emotion_configs.py from\n"
        "# configs/wheel_paper.yaml. Do not hand-edit; edit the spec and regenerate.\n"
        f"# Sofroniew-paper add-on cell for the {spec['track']} track: a behavioural-task\n"
        "# emotion from Sofroniew et al. (2026) with no cell on Plutchik's wheel.\n"
        "# See configs/wheel_paper.yaml for the full cross-reference.\n"
    )

    body: dict[str, object] = {
        "name": cell["name"],
        "label": cell["label"],
        "kind": "paper",
        "paper_label": cell["paper_label"],
        "tasks": list(cell["tasks"]),
    }
    return head + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        help="verify on-disk configs match the spec; write nothing",
    )
    group.add_argument(
        "--list-enabled",
        action="store_true",
        help="print enabled config stems (paper_<name>), one per line; write nothing",
    )
    group.add_argument(
        "--print-track",
        action="store_true",
        help="print the track name from the spec; write nothing",
    )
    args = parser.parse_args()

    spec = load_spec()
    cells = enabled_cells(spec)

    if args.print_track:
        print(spec["track"])
        return 0

    if args.list_enabled:
        for cell in cells:
            print(f"{_PREFIX}{cell['name']}")
        return 0

    if not cells:
        print("no enabled cells in configs/wheel_paper.yaml", file=sys.stderr)
        return 1

    stale = 0
    for cell in cells:
        path = _OUT_DIR / f"{_PREFIX}{cell['name']}.yaml"
        text = render(cell, spec)
        if args.check:
            if not path.exists() or path.read_text() != text:
                print(f"out of date: {path.relative_to(_REPO_ROOT)}")
                stale += 1
        else:
            path.write_text(text)

    if args.check:
        if stale:
            print(f"{stale} config(s) differ from configs/wheel_paper.yaml")
            return 1
        print(f"{len(cells)} paper configs up to date")
        return 0

    names = ", ".join(c["name"] for c in cells)
    print(
        f"wrote {len(cells)} configs to "
        f"{_OUT_DIR.relative_to(_REPO_ROOT)}/{_PREFIX}*.yaml ({names})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
