"""Generate the Plutchik-wheel emotion configs from ``configs/wheel.yaml``.

Writes one Hydra emotion config per wheel corpus to
``configs/emotion/wheel_<name>.yaml`` (33 files: 24 ring cells, 8 dyads,
neutral). The ``wheel_`` filename prefix keeps these in the existing
``emotion`` config group without colliding with the legacy Ekman /
Wilcox / primary-9 configs, nine of which share a cell name (plus
``neutral``).

The generated ``name:`` field is the bare cell name, because
``cfg.emotion.name`` is what the pipeline uses for corpus and activation
filenames; the wheel track is separated by the ``track`` path component
(see ``plans/plutchik-wheel-expansion.md`` §1), not by the cell name.

Usage::

    uv run python scripts/build_wheel_configs.py [--check]

``--check`` regenerates into memory and exits non-zero if any file on
disk differs, for CI.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SPEC = _REPO_ROOT / "configs" / "wheel.yaml"
_OUT_DIR = _REPO_ROOT / "configs" / "emotion"
_PREFIX = "wheel_"

_RING_CODE = {"high": 1, "middle": 2, "low": 3}


def load_spec(path: Path = _SPEC) -> dict:
    """Read and lightly validate ``configs/wheel.yaml``."""
    spec = yaml.safe_load(path.read_text())
    if len(spec["axes"]) != 8:
        raise ValueError(f"expected 8 axes, got {len(spec['axes'])}")
    if len(spec["dyads"]) != 8:
        raise ValueError(f"expected 8 dyads, got {len(spec['dyads'])}")
    return spec


def build_cells(spec: dict) -> list[dict]:
    """Return the 33 cell records (24 ring + 8 dyad + neutral)."""
    cells: list[dict] = []

    for axis in spec["axes"]:
        for ring, cell_name in axis["rings"].items():
            cells.append(
                {
                    "name": cell_name,
                    "label": 100 + 10 * axis["index"] + _RING_CODE[ring],
                    "kind": "ring",
                    "axis": axis["name"],
                    "ring": ring,
                    "opposite_axis": axis["opposite"],
                }
            )

    for dyad in spec["dyads"]:
        cells.append(
            {
                "name": dyad["name"],
                "label": dyad["label"],
                "kind": "dyad",
                "components": list(dyad["components"]),
            }
        )

    cells.append(
        {
            "name": spec["neutral"]["name"],
            "label": spec["neutral"]["label"],
            "kind": "neutral",
        }
    )
    return cells


def render(cell: dict, track: str) -> str:
    """Render one emotion config file."""
    head = (
        "# GENERATED by scripts/build_wheel_configs.py from configs/wheel.yaml.\n"
        "# Do not hand-edit; edit the spec and regenerate.\n"
        f"# Plutchik-wheel extraction track ({track}). "
        "See plans/plutchik-wheel-expansion.md.\n"
    )

    body: dict[str, object] = {"name": cell["name"], "label": cell["label"]}
    if cell["kind"] == "ring":
        body["axis"] = cell["axis"]
        body["ring"] = cell["ring"]
        body["opposite_axis"] = cell["opposite_axis"]
    elif cell["kind"] == "dyad":
        body["components"] = cell["components"]

    note = ""
    if cell["kind"] == "neutral":
        note = (
            "# Reference corpus for this track: used to fit the neutral PCs that\n"
            "# are projected out of every wheel vector, not as an emotion.\n"
        )
    elif cell["kind"] == "dyad":
        note = (
            "# Plutchik primary dyad. Derived independently, on equal footing\n"
            "# with the ring cells; `components` is descriptive metadata and is\n"
            "# not used by the derivation.\n"
        )

    return head + note + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify on-disk configs match the spec; write nothing",
    )
    args = parser.parse_args()

    spec = load_spec()
    cells = build_cells(spec)
    track = spec["track"]

    labels = [c["label"] for c in cells]
    if len(set(labels)) != len(labels):
        raise ValueError("duplicate labels in generated wheel cells")

    stale = 0
    for cell in cells:
        path = _OUT_DIR / f"{_PREFIX}{cell['name']}.yaml"
        text = render(cell, track)
        if args.check:
            if not path.exists() or path.read_text() != text:
                print(f"out of date: {path.relative_to(_REPO_ROOT)}")
                stale += 1
        else:
            path.write_text(text)

    if args.check:
        if stale:
            print(f"{stale} config(s) differ from configs/wheel.yaml")
            return 1
        print(f"{len(cells)} wheel configs up to date")
        return 0

    print(f"wrote {len(cells)} configs to {_OUT_DIR.relative_to(_REPO_ROOT)}/{_PREFIX}*.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
